name: Django CI/CD

on:
  push:
    branches:
      - master  # Adjusted for your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydatabase

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Choose your Python version

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker-compose -f docker-compose.ci.yml up -d
        sleep 30

    - name: Build and test Django app
      run: |
        docker-compose -f docker-compose.ci.yml run web python manage.py test

    - name: Collect static files
      run: |
        docker-compose -f docker-compose.ci.yml run web python manage.py collectstatic --noinput

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to staging
      run: |
        # Add deployment steps here (e.g., deploy to a staging server)
        echo "Deploying to staging..."

    - name: Deploy to production
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        # Add deployment steps here (e.g., deploy to a production server)
        echo "Deploying to production..."
