# Generated by Django 5.0.1 on 2024-01-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoevideo',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='release_date',
        ),
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_images/'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('loafers', 'Loafers'), ('sneakers', 'Sneakers'), ('official', 'Official'), ('sandals', 'Sandals'), ('boots', 'Boots'), ('casual', 'Casual')], default='loafers', max_length=10),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ShoeImage',
        ),
        migrations.DeleteModel(
            name='ShoeVideo',
        ),
    ]
